name: palapa1
description: A new Flutter project.

<<<<<<< HEAD
publish_to: "none"
=======
publish_to: 'none'
>>>>>>> f559091 (fix bug on monitoring)

version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  fl_chart: ^0.55.2
  flutter_native_splash: ^2.2.8
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.2
  omni_datetime_picker: ^0.1.2
  provider: ^6.0.3
  cbor: ^5.0.1
  drift: ^2.2.0
  drift_sqflite: ^2.0.0
  http: ^0.13.4
  pin_code_text_field: ^1.8.0
  flutter_screenutil: ^5.5.4
  firebase_auth: ^3.9.0
  percent_indicator: ^4.2.2
  sign_in_with_apple: ^4.1.0
  android_intent_plus: ^3.1.2
  fluttertoast: ^8.0.9
  vibration: ^1.7.6
  stacked_firebase_auth: ^0.2.16
  firebase_core: ^1.22.0
  video_player: ^2.4.7
  chewie: ^1.3.5
  google_sign_in: ^5.4.1
  unique_identifier: ^0.2.2
  permission_handler: ^10.0.0
  carousel_slider: ^4.1.1
  workmanager: ^0.5.0
  community_material_icon: ^5.9.55
  shared_preferences: ^2.0.15

dev_dependencies:
  drift_dev: ^2.2.0+1
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner:
  lint: ^1.8.2
  flutter_lints: ^1.0.0
flutter_native_splash:
  image: assets/images/login_image.png
  color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
=======
    sdk: '>=2.18.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    google_fonts: ^3.0.1
    fl_chart: ^0.55.2
    flutter_native_splash: ^2.2.8
    url_launcher: ^6.1.5
    cached_network_image: ^3.2.2
    firebase_messaging: ^14.1.3
    omni_datetime_picker: ^0.1.2
    provider: ^6.0.3
    graphic: ^1.0.1
    cbor: ^5.0.1
    drift: ^2.2.0
    drift_sqflite: ^2.0.0
    http: ^0.13.4
    pin_code_text_field: ^1.8.0
    flutter_screenutil: ^5.5.4
    firebase_auth: ^4.1.3
    percent_indicator: ^4.2.2
    sign_in_with_apple: ^4.1.0
    android_intent_plus: ^3.1.2
    fluttertoast: ^8.0.9
    vibration: ^1.7.6
    stacked_firebase_auth: ^0.2.16
    firebase_core: ^2.3.0
    video_player: ^2.4.7
    chewie: ^1.3.5
    get: ^4.6.5
    flutter_local_notifications: ^12.0.4
    google_sign_in: ^5.4.1
    unique_identifier: ^0.2.2
    permission_handler: ^10.0.0
    carousel_slider: ^4.1.1
    community_material_icon: ^5.9.55
    webview_flutter: ^3.0.4
    shared_preferences: ^2.0.15

dev_dependencies:
    drift_dev: ^2.2.0+1
    flutter_localizations:
        sdk: flutter
    flutter_test:
        sdk: flutter
    build_runner:
    lint: ^1.8.2
    flutter_lints: ^1.0.0
flutter_native_splash:
    image: assets/images/login_image.png
    color: '#ffffff'

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/lang/
>>>>>>> f559091 (fix bug on monitoring)
